from __future__ import annotations

from pathlib import Path
import os

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLBACKEND", "Agg")
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".matplotlib"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler


RANDOM_STATE = 42
TSNE_GENERATED_SAMPLE_SIZE = 247


def flatten_windows(x: np.ndarray) -> np.ndarray:
    return x.reshape(x.shape[0], -1)


def sample_windows(x: np.ndarray, n_sample: int, seed: int) -> np.ndarray:
    if len(x) <= n_sample:
        return x
    rng = np.random.default_rng(seed)
    return x[rng.choice(len(x), size=n_sample, replace=False)]


def load_x(path: Path) -> np.ndarray:
    return np.load(path, allow_pickle=True)["X"].astype(np.float32)


def split_real_points_by_overlap(
    real_points: np.ndarray,
    gen_points: np.ndarray,
    threshold: float = 1.4,
) -> tuple[np.ndarray, np.ndarray]:
    distances, _ = NearestNeighbors(n_neighbors=1).fit(gen_points).kneighbors(real_points)
    overlap_mask = distances[:, 0] <= threshold
    return real_points[overlap_mask], real_points[~overlap_mask]


def main() -> None:
    split_dir = ROOT / "data" / "augmentation_split"
    generated_dir = ROOT / "data" / "research02" / "generated"
    figure_dir = ROOT / "data" / "research02" / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    (ROOT / ".matplotlib").mkdir(parents=True, exist_ok=True)

    real_x = load_x(split_dir / "anomaly_train_seed_windows.npz")
    generated_sets = {
        "GT-GAN": load_x(generated_dir / "gtgan_series_windows.npz"),
        "Masking GT-GAN": load_x(generated_dir / "gtgan_masked_windows.npz"),
        "Diffusion": load_x(generated_dir / "diffusion_series_windows.npz"),
        "Masking Diffusion": load_x(generated_dir / "diffusion_masked_windows.npz"),
    }
    sampled_generated_sets = {
        name: sample_windows(generated_x, TSNE_GENERATED_SAMPLE_SIZE, seed=RANDOM_STATE + i)
        for i, (name, generated_x) in enumerate(generated_sets.items())
    }

    arrays = [flatten_windows(real_x)]
    labels = ["Real Data"] * len(real_x)
    for name, generated_sample in sampled_generated_sets.items():
        arrays.append(flatten_windows(generated_sample))
        labels.extend([name] * len(generated_sample))

    labels = np.asarray(labels)
    x_scaled = StandardScaler().fit_transform(np.vstack(arrays))
    perplexity = min(30, max(5, (len(x_scaled) - 1) // 3))
    embedded = TSNE(
        n_components=2,
        perplexity=perplexity,
        learning_rate="auto",
        init="pca",
        random_state=RANDOM_STATE,
    ).fit_transform(x_scaled)

    real_points = embedded[labels == "Real Data"]
    x_min, x_max = embedded[:, 0].min(), embedded[:, 0].max()
    y_min, y_max = embedded[:, 1].min(), embedded[:, 1].max()
    x_pad = max((x_max - x_min) * 0.06, 1.0)
    y_pad = max((y_max - y_min) * 0.06, 1.0)
    x_limits = (x_min - x_pad, x_max + x_pad)
    y_limits = (y_min - y_pad, y_max + y_pad)

    titles = {
        "GT-GAN": "Data generated by GT-GAN t-SNE",
        "Masking GT-GAN": "Data generated by masking-GT-GAN t-SNE",
        "Diffusion": "Data generated by Diffusion Model t-SNE",
        "Masking Diffusion": "Data generated by Masking-based Diffusion t-SNE",
    }

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes = axes.ravel()
    for i, (name, _generated_sample) in enumerate(sampled_generated_sets.items()):
        gen_points = embedded[labels == name]
        real_overlap, real_non_overlap = split_real_points_by_overlap(real_points, gen_points)
        ax = axes[i]
        ax.scatter(
            gen_points[:, 0],
            gen_points[:, 1],
            s=46,
            alpha=0.72,
            label="Generated Data",
            color="#0066CC",
            marker="o",
            edgecolor="white",
            linewidth=0.35,
            zorder=2,
        )
        ax.scatter(
            real_non_overlap[:, 0],
            real_non_overlap[:, 1],
            s=46,
            alpha=0.72,
            label="Real Data non-overlap",
            color="#FF7F0E",
            marker="o",
            edgecolor="white",
            linewidth=0.35,
            zorder=3,
        )
        ax.scatter(
            real_overlap[:, 0],
            real_overlap[:, 1],
            s=72,
            alpha=0.98,
            label="Real Data overlap",
            facecolors="none",
            marker="o",
            edgecolor="#FF7F0E",
            linewidth=1.25,
            zorder=5,
        )
        ax.set_title(f"{titles[name]}\nReal n={len(real_points)}, Generated n={len(gen_points)}", fontsize=10, fontweight="bold")
        ax.set_xlim(x_limits)
        ax.set_ylim(y_limits)
        ax.set_aspect("equal", adjustable="box")
        ax.legend(fontsize=8)
        ax.grid(False)

    out_path = figure_dir / "tsne_2x2_real_vs_generated_full.png"
    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)
    print(out_path)


if __name__ == "__main__":
    main()
